export default {
  INITIAL_LAUNCH_SCREEN_BG_PINK: "#DF57C1",
  ONBOARDING_BG_BRIGHT_GREEN: "#87FFCD",
  ONBOARDING_BG_BRIGHT_BLUE: "#22CFE7",
  ONBOARDING_BG_PURPLE: "#8C0FEE",
  INITIAL_LAUNCH_SCREEN_TEXT_WHITE: "#FFFFFF",
  SIGN_IN_TEXT_BLACK: "#000000",
  INITIAL_LAUNCH_SCREEN_ARROW_WHITE: "#FFFFFF",
  TYPE_PLACEHOLDER_TEXT_COLOR: "rgba(255, 255, 255, 0.7)",

  // modal attributes
  BOOK_INFO_MODAL_GREY_LINE_COLOR: "#D3D3D3",

  BUTTON_PURPLE: "#5B2FA3",
  BUTTON_GRAY: "#F7F7F7"
};
