export default {
  INITIAL_LAUNCH_SCREEN_BG_PINK: "#DF57C1",
  ONBOARDING_BG_BRIGHT_GREEN: "#87FFCD",
  ONBOARDING_BG_BRIGHT_BLUE: "#22CFE7",
  ONBOARDING_BG_PURPLE: "#8C0FEE",
  INITIAL_LAUNCH_SCREEN_TEXT_WHITE: "#FFFFFF",
  SIGN_IN_TEXT_BLACK: "#000000",
  INITIAL_LAUNCH_SCREEN_ARROW_WHITE: "#FFFFFF",
};
