export default {
  // Initial launch screen
  INITIAL_LAUNCH_SCREEN_BOTTOM_MARGIN: -100,
  INITIAL_LAUNCH_SCREEN_TITLE: 70,
  INITIAL_LAUNCH_SCREEN_TITLE_TOP_MARGIN: 350,
  INITIAL_LAUNCH_SCREEN_TEXT: 20,
  INITIAL_LAUNCH_SCREEN_TEXT_MARGIN: 10,
  INITIAL_LAUNCH_SCREEN_TEXT_SIDE_MARGIN: 50,
  INITIAL_LAUNCH_SCREEN_NEXT_ARROW_SIZE: 60,
  INITIAL_LAUNCH_SCREEN_NEXT_ARROW_TOP_MARGIN: 40,
  NAVBAR_ICON_SIZE: 35,

  // book info modal attributes
  BOOK_INFO_MODAL_GREY_LINE_MARGIN_TOP: 10,
  BOOK_INFO_MODAL_MARGIN_TOP: "70%",
  BOOK_INFO_MODAL_MARGIN_LEFT: -20,
  BOOK_INFO_MODAL_MARGIN_RIGHT: -29,

  BOOK_INFO_MODAL_COVER_WIDTH: 105,
  BOOK_INFO_MODAL_COVER_HEIGHT: 160,
  // BOOK_INFO_MODAL_COVER_MARGIN_TOP: -200,
  BOOK_INFO_MODAL_COVER_MARGIN_TOP: "80%",
  BOOK_INFO_MODAL_COVER_MARGIN_BOTTOM: 10,
  BOOK_INFO_MODAL_TITLE_FONT_SIZE: 20,
  BOOK_INFO_MODAL_TITLE_MARGIN_BOT: 0,
  BOOK_INFO_MODAL_AUTHOR_FONT_SIZE: 16,
  BOOK_INFO_MODAL_COVER_RADIUS: 6,
  BOOK_INFO_MODAL_SUMMARY_MARGIN: 10,
};
