export default {
  INITIAL_LAUNCH_SCREEN_TITLE: 70,
  INITIAL_LAUNCH_SCREEN_TEXT: 20,
  INITIAL_LAUNCH_SCREEN_TEXT_MARGIN: 10,
  INITIAL_LAUNCH_SCREEN_TEXT_SIDE_MARGIN: 50,
  INITIAL_LAUNCH_SCREEN_NEXT_ARROW_SIZE: 60,
  INITIAL_LAUNCH_SCREEN_NEXT_ARROW_TOP_MARGIN: 40,
  NAVBAR_ICON_SIZE: 35,
};
