export default {
  genres: [
    "Antiques & Collectibles",
    "Literary Collections",
    "Architecture",
    "Literary Criticism",
    "Art",
    "Mathematics",
    "Bibles",
    "Medical",
    "Biography & Autobiography",
    "Music",
    "Body, Mind & Spirit",
    "Nature",
    "Business & Economics",
    "Performing Arts",
    "Comics & Graphic Novels",
    "Pets",
    "Computers",
    "Philosophy",
    "Cooking",
    "Photography",
    "Crafts & Hobbies",
    "Poetry",
    "Design",
    "Political Science",
    "Drama",
    "Psychology",
    "Education",
    "Reference",
    "Family & Relationships",
    "Religion",
    "Fiction",
    "Science",
    "Foreign Language Study",
    "Self-Help",
    "Games & Activities",
    "Social Science",
    "Gardening",
    "Sports & Recreation",
    "Health & Fitness",
    "Study Aids",
    "History",
    "Technology & Engineering",
    "House & Home",
    "Transportation",
    "Humor",
    "Travel",
    "Juvenile Fiction",
    "True Crime",
    "Juvenile Nonfiction",
    "Young Adult Fiction",
    "Language Arts & Disciplines",
    "Young Adult Nonfiction",
    "Law",
  ]
};